name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "build.yaml"
      - "boards/**"
      - "config/**"
      - ".github/workflows/build.yml"
    tags-ignore:
      - "*"
  pull_request:
    paths:
      - "build.yaml"
      - "boards/**"
      - "config/**"
      - ".github/workflows/build.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
